name: Publish Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@igorganapolsky'
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build packages
        run: yarn build
        
      - name: Publish packages
        run: |
          echo "Publishing packages with debug information"
          # Ensure all packages have the right publishConfig
          find packages -name "package.json" -exec sed -i 's/"publishConfig": {/"publishConfig": {\n    "registry": "https:\/\/npm.pkg.github.com\/",/g' {} \;
          
          # Add verbose flag for better error messages
          cd packages/types
          yarn publish --access public --verbose || true
          cd ../core
          yarn publish --access public --verbose || true
          cd ../api
          yarn publish --access public --verbose || true
          cd ../hooks
          yarn publish --access public --verbose || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
